apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:d0MlztStkbS3KHNy03mRNgkH3z1gA67F3wwl3x74ULgTvivkxoVzzg==,iv:Pd5VZ6DOQZYlYBlT0hU+tzyFxqr4LyawVsuUvB6FtvY=,tag:vVv75XYp2XyASwuc4qqtqQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hzty67cumgjz0xrt03cdlugx0r4fm6dx8d5ud0dcq3nnlvfuj4kqwvntqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYnU5NXVJSnRLSWR4YkNP
            NTc0OEJRR1Z6VkY2bGtKL3FOakg0L0ZWZ2lJClRRay9MdUNlSUp4cTM2UjZlbzVQ
            bnQxRTIxd1lGUSs3cVdYL0MyM1REMDgKLS0tIHk0TnFTeDZuNU84YnpjRStYNkRB
            VU9QbnIwMC9adVAwdUd4MzJQbXRqS3MKXZH+ByHtADeDSJOAmPnjRoOAwnP7jmrN
            S21Lp45DZ4xmU4c7YGaGsHcpQHJA6NPSCyqM0Eb38Bn94AriRkSJmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-11T16:15:34Z"
    mac: ENC[AES256_GCM,data:bgiiP1KO5d5NXnr2MpgR4gevuhoYnP3OB9JT9HcBPVN7oN1k/92wNrkb1xJJKWZYKzfNDYe/PN+gOCwJEsKmYTq5/TxuzMJ9yBUfymTDJw4lN1go0/d2Z5yAgsOMBpb2ls9Mmoc7bL9gEhYVVaJv2dX5WGkYmBC+HZGXpNjj0zM=,iv:Wjx8K4iItAcuRwvpAioCru2wyLvL9mtDhsJK7d8ol8g=,tag:lqWE+RbshNmZj2t7lpmJFg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
