apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:IiNjmowcqHYR2Dqz9CJ3ULf8Sg73jT3WuawkoE1PzAUZTroTSEf7GA==,iv:UDg4BP7U7f5JAv2c2trI9g1ifnGkJ/kHECK5tlARkzE=,tag:GP+bc6U2hRe2y5GPi0rPcg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hzty67cumgjz0xrt03cdlugx0r4fm6dx8d5ud0dcq3nnlvfuj4kqwvntqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTXdTc0NGbkxJeG1OaUxP
            OERSdDVqK0JBcjNWeW5SR1J4L2EvcFVVV2prCkhVb0NZektKbGU4RXhxcDdPc250
            K1Y4dzR3RFNreDVCOGIvb2paWWRWNlEKLS0tIHNMbDh5dHlPTWNHMEN5elA3QThH
            anBtTUNLQmtJME5HYTlnRVFBZDZMQ0kKSYzpwc04vybCeGthIliy8I6bQsy9g1lr
            VDtVyxHbzUyvsQJeTB/Wgy2G7B8vhWRX1KGMbRGywMhyKck6U+HRjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-08T08:32:57Z"
    mac: ENC[AES256_GCM,data:NuP32x/MPSG8dwS20WcWz54H7NlDHG4twzBt3QbbfaUHLSHXO1IuTbiqR/3RKEcOiVAz64ypQFldBUEPi+oW2aiJx4l9KnpHa0Gt3bCNm+ZnRYHpixtCAtI21X/24FZ+RWhAA0Y5ck0tap/WLv2BFDopreYE8Yi68UISI5x5YBg=,iv:5SmbLMs9tMOoovy07dOAdiYGN0Usm0q/4y1+9pvWskU=,tag:I132mBoPJNmV3M/vFOThSw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
