apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:RZwEaO+GgGd2oO6BlhrhUU2dtm6a47wnvcLqtEvY/kBwj4dinuhCCg==,iv:3OEr6XsvJR6dMOgPNehjOb1013YhxrwsNQfUyPOjUnE=,tag:M2n4tMbcRg8V0Inob4aopQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hzty67cumgjz0xrt03cdlugx0r4fm6dx8d5ud0dcq3nnlvfuj4kqwvntqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4clU0RHdPdDhkT1lYTndY
            OFNLMllyaHdNNnNsOStYWkVhS2ZDZ3N0cFhvCk96c2RUUFhVbTJJUWNBaks1UWxB
            bm1JNEtrajJQZ3hiUDAvYlQvM1dLRFkKLS0tIHhxRnY4M0szRVBHemx2K2F4SlZi
            WjN0YkZmK0c0RWc0bnVRVnVlNU5wVzgKSRNlaqREgwF/8Ss5CzzTdLifN48UppZb
            EkJHB8MHdSAJP1gYgHAONpP+RD4ciHYWwxocRNm+gogd/j+jAkT16w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-13T08:56:58Z"
    mac: ENC[AES256_GCM,data:zamqX48EVjbO4iUJfChLslSRI25LJrp7AP/tf2hr38PkX/6m7/TCZY9Mk+IAn3ZQ5kVZpZiKzXgPQoGERdov+SS2E7EDIvgHoe+8crBsCxZLdtt1ZyugmhAKNJoRU3mtsqxW+OZWhhsr39b40LmL/bx6GtekDRcmC/mbe4RhdF0=,iv:X+xwAx82c24iyIiU36Ncpf+Q8KxE07v70qbQkCBivhc=,tag:E0hBi9U6Km9rbCEkBvlT+Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
