apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TF2x2jSm9E20az3W97V5lhqEuTKXbnScXrcSAI4rByvaiJW5uuebnFWZR/0ptN1Lcgg5+9B5P0GTR1ctX1+lM6JTM06FgCc7P1AlNsBw2aYnFh+zWxO/qpK6MNFYt90lu0O8jSA27e7OjGFuOIqv/kU+cHSzJtoNK5a/XomxvoE9lyGE1pn25dR90DuFGYPQ9KPN64LGDhJILCRjs5ekPTILJ7DVtwQXoaWxzAmduV2drZFGPMWKNk1BQ88l8TYammeAYCTAUxUzb7pIs0FAMPMey9PfWuOvqIvBnTvob9sWMCkhFN98DI7Nv3xYlzLCd9loSnUJrryeypqigY7qlbbtQEe+2e8hye+Ovh2fQ8uhgfin+Qu+jzSzFmkz3Or6,iv:CZuRrQAMOVmTWwco0N7SYYSYbjVaaW1m1bntwyeNxeE=,tag:QbsDMIOyNdRRSxQF6T3uKw==,type:str]
    identity.pub: ENC[AES256_GCM,data:SdW/SuHmK9sFYX8nff3OgANL44YwJELG2jXocIiRdeqMIZDs5DjSiPEU2sMJ8ElcrQFV9e/ZfBfsMK1XGYOF2+dmGMDCIf7aUNI0CZBHPRpO6HzDfzkI4KuwK2bB/a+yGPABUUCQqzJrgrWn5ikgBlUwvxWrfGQZC5+La5QOMUf7wjws+pLVLwoBNgXbXfzK31RMCI1mK+OdNWmnL2W/NxqMvj8hY0D8p/36Iwv9l51wu4iGp+RJDkzxikr0g0lYA9yUaztHmrAzrUKSUw==,iv:JVM+9lMz1geDTN2+1kxYLHLhCREeol+H5DxipQqq7WE=,tag:LILeTQxewxXbvTwGTV182g==,type:str]
    known_hosts: ENC[AES256_GCM,data:lH8kzV2/es+9eWplXxtumy2ce2c7SKW6jF/Cyzl0dfLIZhkE9t3JgNqT8imP8rvFytd4NJjuPTuC8rH9J3cj/kqtxw1w6io0T+OAKfql/5Caaz/FdWCgvsSmNZcIvdmOm8gwrr2Z+wl6BHFkazC5hhFDXHmKb2JNd5a2gCfQ3u/UATRUgCVnuxcqQR2m9DKyOs2wFB6JLyYNIaAdSnG2vBjjMYk5hm64885G,iv:tQPkg17a0/0NpXfOWPUK9Cf8tBX8Z3PDtZMXtsj4RNI=,tag:XYJOSnhXKEw+6Qw2Ti+Gaw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hzty67cumgjz0xrt03cdlugx0r4fm6dx8d5ud0dcq3nnlvfuj4kqwvntqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBST3U1S1BHeDVobWtXL1J3
            b3BFYVU4aWlQeStZZTRNVlFqUVJGdEhjd21nCitJRUpJRGV5UUpTL0ZVTitwcTgz
            cUJ1MVF5QUNkOU95Sk5PRTRMU0pUNTgKLS0tIDcySkExSGVQZUc5TlZqNDl3cDUv
            MkdrOHFtNThJaTRTd3V0aHkxWVQ4YVEKc1Wzz1OZZ75NB1RBMQR473271IAuYW2T
            0NJg9gGb0m8JHT/6D0tVEib3QuywFtUEv38XUFec8eZda3Fv4lXG/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-08T08:32:57Z"
    mac: ENC[AES256_GCM,data:33nc+g2JVDMz60Z4XSG1askZedyNur9qvitSwlfA1p5CeRgAuQCvsQFKAuczqJFlzrOhmiiGwVkpg5Cqp3vr63LCBOPnx/QzjJzS2R8REWIs13qcYjF+OnEvzxX0Sj8+9y3lylkrmAzt6VAa0VHGtQ4JVEt/alC/yGieArthB5o=,iv:9cvpzpUUtwDd9BgUI+x0mFqoVjtVLOXL9PJlMC2he88=,tag:JurRjDDz6eaCvuBVEu1QAw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
